export type Translation = ({ key: string, def: string })[];


export interface Definition {
    def: string;
    synonyms?: string[];
}

export const beerDict = {
    "lager": {
        def: "Светлый пивас",
        synonyms: ["лагер"]
    },
    "pilsner": {
        def: "Светлый пивас с горчинкой",
        synonyms: ["пильзнер", "пилзнер"]
    },
    "stout": {
        def: "Темный пивас на основе жженого солода",
        synonyms: ["стаут"]
    },
    "hazelnut": {
        def: "С запахом/нотками ореха",
        synonyms: ["nut", "nutty", "ореховый"]
    },
    "weisse": {
        def: "Пшеничный пивас"
    },
    "passion fruit": {
        def: "Пиво с маракуей, очевидно кисленькое",
        synonyms: ["маракуйя"]
    },
    "berliner": {
        def: "Кисленькая пшеничка"
    },
    "ipa": {
        def: "Indian Pale Ale - охмеленный эль, обычно горький на вкус и пахнет цитрусовыми",
        synonyms: ["ипа", "ипашка"]
    },
    "cloudy": {
        def: "Мутное",
    },
    "ddh": {
        def: "double dry hopped - дважды охмеленный, после выброжения"
    },
    "citra": {
        def: "Вид хмеля",
        synonyms: [
            "astra",
            "eclipse",
            "ella",
            "enigma",
            "feux-coeur francais",
            "galaxy",
            "helga",
            "hpa-016",
            "melba",
            "pride of ringwood",
            "summer",
            "super pride",
            "sylva",
            "topaz",
            "vic secret",
            "vienna gold",
            "canadian redvine",
            "lumberjack",
            "sasquatch",
            "wild loyalist",
            "marco polo",
            "tsingdao flower",
            "agnus",
            "amethyst",
            "bohemie",
            "boomerang",
            "bor",
            "gaia",
            "harmonie",
            "kazbek",
            "mimosa",
            "premiant",
            "saaz",
            "sládek",
            "vital",
            "aramis",
            "barbe rouge",
            "bouclier",
            "elixir",
            "mistral",
            "petit blanc",
            "strisselspalt",
            "tardif de bourgogne",
            "triskel",
            "akoya",
            "ariana",
            "aurum",
            "brewer's gold",
            "callista",
            "diamant",
            "hallertau blanc",
            "hallertau gold",
            "hallertau mittelfrüh",
            "hallertau tradition",
            "herkules",
            "hersbrucker",
            "huell melon",
            "hüller bitterer",
            "magnum",
            "mandarina bavaria",
            "merkur",
            "monroe",
            "northern brewer",
            "opal",
            "orion",
            "perle",
            "polaris",
            "relax",
            "saphir",
            "smaragd",
            "solero",
            "spalt",
            "spalter select",
            "tango",
            "tettnanger",
            "wurttemberg",
            "yellow sub",
            "golden star",
            "sorachi ace",
            "toyomidori",
            "brooklyn",
            "dr. rudi",
            "green bullet",
            "hort9909",
            "kohatu",
            "motueka",
            "moutere",
            "nectaron",
            "nelson sauvin",
            "nzh-107",
            "pacific gem",
            "pacific jade",
            "pacific sunrise",
            "pacifica",
            "rakau",
            "riwaka",
            "smooth cone",
            "southern cross",
            "sticklebract",
            "taiheke",
            "wai-iti",
            "waimea",
            "wakatu",
            "junga",
            "limbus",
            "lubelska",
            "magnat",
            "marynka",
            "pulawski",
            "sybilla",
            "zula",
            "apolon",
            "atlas",
            "aurora",
            "bobek",
            "cekin",
            "celeia",
            "dana",
            "styrian cardinal",
            "styrian dragon",
            "styrian eagle",
            "styrian fox",
            "styrian golding",
            "styrian kolibri",
            "styrian wolf",
            "african queen",
            "southern",
            "southern brewer",
            "southern dawn",
            "southern pas,sion",
            "southern promise",
            "southern, star",
            "southern sub,lime",
            "southern tropic",
            "xja2/436",
            "zagrava",
            "admiral",
            "archer",
            "beata",
            "boadicea",
            "bramling cross",
            "challenger",
            "defender",
            "east kent goldings",
            "endeavour",
            "epic",
            "ernest",
            "first gold",
            "flyer",
            "fuggle",
            "godiva",
            "taurus",
            "harlequin",
            "herald",
            "jester",
            "minstrel",
            "mystic",
            "olicana",
            "omega",
            "phoenix",
            "pilgrim",
            "pilot",
            "pioneer",
            "progress",
            "sovereign",
            "sussex",
            "target",
            "wgv",
            "yeoman",
            "adeena",
            "ahhhroma",
            "ahtanum",
            "aloha blend",
            "altus",
            "amarillo",
            "apollo",
            "aquila",
            "arcadian",
            "azacca",
            "banner",
            "belma",
            "bergamot",
            "bianca",
            "bitter gold",
            "bravo",
            "brewer's gold",
            "bru-1",
            "bullion",
            "buzz bullets",
            "caliente",
            "calypso",
            "cascade",
            "cashmere",
            "centennial",
            "chelan",
            "chinook",
            "citra",
            "cluster",
            "cluster fugget blend",
            "columbia",
            "columbus",
            "comet",
            "contessa",
            "crystal",
            "ctz",
            "delta",
            "diamond springs",
            "ekuanot",
            "el dorado",
            "emerald spire",
            "equinox",
            "eroica",
            "eureka",
            "evergreen blend",
            "falconer's flight",
            "fantasia blend",
            "galena",
            "gemini",
            "glacier",
            "golding",
            "grungeist",
            "hallertau",
            "hartwick",
            "hbc 472",
            "hbc 586",
            "hbc 630",
            "hbc 692",
            "helios",
            "horizon",
            "hydra",
            "idaho 7",
            "idaho gem",
            "independence",
            "jarrylo",
            "lambic",
            "lawton",
            "lemondrop",
            "liberty",
            "loral",
            "lotus",
            "mackinac",
            "magnum",
            "mckenzie",
            "medusa",
            "meridian",
            "michigan copper",
            "millennium",
            "mosaic",
            "mount hood",
            "mount rainier",
            "multihead",
            "newport",
            "nobility blend",
            "northdown",
            "northern brewer",
            "nugget",
            "old mission",
            "olympic",
            "pacific crest",
            "pahto",
            "palisade",
            "paradigm",
            "pekko",
            "perle",
            "petoskey",
            "prussian",
            "saaz",
            "sabro",
            "samba",
            "santiam",
            "satus",
            "saugatuck",
            "sequoia blend",
            "shaddock",
            "simcoe",
            "sitiva blend",
            "sonnet",
            "sterling",
            "sticky fingers blend",
            "stirling",
            "strata",
            "sultana",
            "summit",
            "sun",
            "sunbeam",
            "super galena",
            "tahoma",
            "talisman",
            "talus",
            "teamaker",
            "tettnang",
            "tillicum",
            "tnt blend",
            "tomahawk",
            "trident",
            "triplepearl",
            "triumph",
            "tropica",
            "ultra",
            "usda 008",
            "vanguard",
            "vista",
            "walhalla",
            "warrior",
            "wild wolf",
            "willamette",
            "x13459",
            "yakima cluster",
            "yakima gold",
            "yqh-1380",
            "zamba blend",
            "zappa",
            "zenia",
            "zenith",
            "zeus",
            "zythos",
        ]
    }
};