POST https://functions.yandexcloud.net/d4egqbhi7fbj2euj7tca
Content-Type: application/json

{
  "id": 170653031,
  "first_name": "Nikita",
  "last_name": "Leybovich",
  "username": "potykion",
  "photo_url": "https://t.me/i/userpic/320/kZRjFa2_YxDfV4kebCnJC7bkap85DQK3eh-sRTQjDuo.jpg",
  "auth_date": 1720444043,
  "hash": "6d44c1214ab16b9f4f3ae09f760166cc51e11740293ca34089461e5eec09cb1b"
}
