backend:
  name: git-gateway
  branch: master

media_folder: "docs"
collections:
  - name: "blog"
    label: "Blog"
    folder: "docs"
    create: true
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}'
    #      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    slug: "{{slug}}"
    fields:
      #        - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      #        - { label: "Publish Date", name: "date", widget: "datetime" }
      #        - { label: "Featured Image", name: "thumbnail", widget: "image" }
      #        - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }