backend:
  name: git-gateway
  branch: master

media_folder: "docs"
collections:
  - name: "blog"
    label: "Blog"
    folder: "docs"
    create: true
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}'
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
    meta: { path: { widget: string, label: 'Path', index_file: 'index' } }
