name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - env:
          GA_KEY: ${{ secrets.GA_KEY }}
          YA_METRICA_KEY: ${{ secrets.YA_METRICA_KEY }}
        run: mkdocs gh-deploy --force
