name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - env:
          GA_KEY: ${{ secrets.GA_KEY }}
          YA_METRICA_KEY: ${{ secrets.YA_METRICA_KEY }}
        run: mkdocs gh-deploy --force
  keep-board-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: https://storage.yandexcloud.net
          AWS_REGION: 'ru-central1'
          SOURCE_DIR: 'toys/keep-board/keep_board_front'
  keep-board-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@v2
        with:
          token: ${{ secrets.YA_CLI_TOKEN }}
          function_id: ${{ secrets.YA_CLOUD_FUNCTION }}
          runtime: 'python39'
          entrypoint: 'cloud_function.handler'
          source: 'toys/keep-board/keep_board_back'
          environment: GOOGLE_EMAIL=${{ secrets.GOOGLE_EMAIL }},GOOGLE_APP_PASS=${{ secrets.GOOGLE_APP_PASS }},GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}