name: Generate and Push Docs

on:
 push:
    branches:
      - master

jobs:
 build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Locale
        run: |
          sudo apt-get update && sudo apt-get install -y language-pack-ru
          sudo locale-gen ru_RU
          sudo localectl set-locale LANG="ru_RU"
          export LANG="ru_RU"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for the gh-pages branch

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to generate docs
        run: python render_all.py

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout gh-pages branch
        run: |
          git checkout gh-pages || git checkout -b gh-pages

      - name: Pull latest changes from gh-pages
        run: |
          git pull origin gh-pages --allow-unrelated-histories

      - name: Add and commit changes
        run: |
          git add docs/
          git commit -m "Update docs"

      - name: Push to gh-pages branch
        run: |
          git push origin gh-pages
